"""empty message

Revision ID: 041c369d1bd1
Revises: 690046e98ef9
Create Date: 2023-01-25 14:46:52.029261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041c369d1bd1'
down_revision = '690046e98ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchpokemon',
    sa.Column('Search_id', sa.Integer(), nullable=False),
    sa.Column('Pokemon_Name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('Search_id'),
    sa.UniqueConstraint('Pokemon_Name')
    )
    op.create_table('catchpokemon',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_name'], ['searchpokemon.Pokemon_Name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('search_pokemon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_pokemon',
    sa.Column('Search_id', sa.INTEGER(), server_default=sa.text('nextval(\'"search_pokemon_Search_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Pokemon_Name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Search_id', name='search_pokemon_pkey'),
    sa.UniqueConstraint('Pokemon_Name', name='search_pokemon_Pokemon_Name_key')
    )
    op.drop_table('catchpokemon')
    op.drop_table('searchpokemon')
    # ### end Alembic commands ###
