"""empty message

Revision ID: 690046e98ef9
Revises: 74e742894922
Create Date: 2023-01-24 09:53:33.183358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690046e98ef9'
down_revision = '74e742894922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_pokemon',
    sa.Column('Search_id', sa.Integer(), nullable=False),
    sa.Column('Pokemon_Name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('Search_id'),
    sa.UniqueConstraint('Pokemon_Name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_pokemon')
    # ### end Alembic commands ###
